# Tasks

- [/] Project Initialization
    - [x] Create Next.js App (App Router, TypeScript)
    - [x] Set up basic folder structure
    - [x] Configure Vanilla CSS / CSS Modules
- [x] Database & Backend Setup
    - [x] Define Supabase Schema (SQL)
    - [x] Set up Supabase Client
    - [x] Implement RLS Policies
- [ ] Authentication (Phase 1)
    - [ ] Implement Auth (Clerk or NextAuth - TBD)
    - [ ] University Domain Verification Logic
- [ ] User Profile & AI (Phase 2)
    - [ ] Profile Schema & UI
    - [ ] PDF Upload & Gemini Parsing
    - [ ] Vector Embedding Setup (pgvector)
- [ ] Matching Engine (Phase 3)
    - [ ] Recommendation API
    - [ ] Search Functionality
- [ ] Community & Realtime (Phase 4)
    - [ ] Boards
    - [ ] Messaging (Realtime)
